version: "3.9"

services:
  db:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    hostname: minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: password
    volumes:
      - datastore:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server --console-address :9001 /data

volumes:
  pgdata: { }
  datastore: { }